### ISSUE TITLE
Two Questions

### ISSUE THREAD

**Issue by scottrick** [rob-pilkington/XWLoader#3]
Two quick questions:

**Hardpoint**:  What is a hard point?  What is it used for?

LFD docmentation: The wiki refers to "see the LFD format documented earlier".  I don't see any other pages in the wiki, so I'm guessing that is a WIP?

**Comment by rob-pilkington** [comment]
I probably need a better identifier for the "hardpoints." They define the coordinates and properties of components on a model. They can include things that could be called hardpoints, like primary and secondary weapons, and other things that aren't really hardpoints like docking points (which can point to coordinates outside the model).

The format document still needs to be cleaned up some, yes. I originally wrote it in a different context and it seems I missed removing some references (and I know I missed reapplying some formatting in moving to Markdown).

**Comment by scottrick** [comment]
Thanks for the info!
